name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: ElMarcelFarias/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ ElMarcelFarias }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
